# Generated by Django 2.1.7 on 2019-05-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='type',
            field=models.CharField(choices=[('01', 'ลากิจ'), ('02', 'ลาป่วย')], default='01', max_length=2),
        ),
    ]
