# Generated by Django 2.1.7 on 2019-05-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0002_auto_20190501_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='approve_status',
            field=models.CharField(choices=[('รอการอนุมัติ', 'รอการอนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ'), ('อนุมัติ', 'อนุมัติ')], default='อนุมัติ', max_length=3),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='type',
            field=models.CharField(choices=[('ลากิจ', 'ลากิจ'), ('ลาป่วย', 'ลาป่วย')], default='01', max_length=2),
        ),
    ]
