# Generated by Django 2.1.7 on 2019-05-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0004_auto_20190501_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='approve_status',
            field=models.CharField(choices=[('รอการอนุมัติ', 'รอการอนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ'), ('อนุมัติ', 'อนุมัติ')], default='รอการอนุมัติ', max_length=50),
        ),
    ]
